### ISSUE TITLE
Source for indicator 2.a.2

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#10]
Old GIF links to a data set that shows ODA but agricultures is not one of the sectors that ODA is broken down by. Unsure of where the number in the GIF comes from in this data.

**Comment by catherinemichaud** [comment]
I was able to find ODA for Agriculture and Total OOF but not ODA+OOF for Ag. Let's ask Duane for his contact info.

**Comment by catherinemichaud** [comment]
Ok, we don't have any contact for this one. Let's see if we can find it here: https://www.international.gc.ca/gac-amc/publications/odaaa-lrmado/sria-rsai.aspx?lang=eng&_ga=2.213975829.340912999.1620834816-2016260363.1604978633
If not, let's ask Cara she might remember who they talked to.

**Comment by catherinemichaud** [comment]
This is the data source: https://stats.oecd.org/Index.aspx?DataSetCode=CRS1
and use these selections:
Donor = Canada
Sector = 311: III.1.a Agriculture, Total
Channel = All Channels
Flow type = Gross Disbursements
Type of aid = All types, Total

**Comment by MaiaPelletier** [comment]
Done in 2cc49ed56f707ce2e4e89e409495721d3280b3d6
