### ISSUE TITLE
Data update for 17.2.1

### ISSUE THREAD

**Issue by JulienSTC** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#122]
Indicator should be 2 series, 1 for total and 1 for the share sent to least developed countries
Data for Canada are here: https://www.oecd-ilibrary.org/sites/2dcf1367-en/1/3/2/5/index.html?itemId=/content/publication/2dcf1367-en&_csp_=177392f5df53d89c9678d0628e39a2c2&itemIGO=oecd&itemContentType=book

**Comment by MaiaPelletier** [comment]
done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/d1670f87cc8796ab6d1be9e7464aab08ac1fcd41
