### ISSUE TITLE
Data update 8.1.1

### ISSUE THREAD

**Issue by catherinemichaud** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#125]
Please review and confirm methodology as per Request_Indicators_2022_XLSX file in data gap folder

**Comment by MaiaPelletier** [comment]
done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/b0620b10e93e92bf398c3dc5626ee8421ed75f4d

methodology was correct but old GIF previously reported indicator using constant dollars, rather than chained
