### ISSUE TITLE
GRIP 10.7.3

### ISSUE THREAD

**Issue by JulienSTC** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#162]
Potential: https://missingmigrants.iom.int/region/americas
US/CAN border data available

**Comment by catherinemichaud** [comment]
SME does not recommend usign that data

**Comment by JulienSTC** [comment]
FR Page: 

- [ ] def and concepts: L'indicateur mesure le nombre de personnes décédées ou disparues au cours du processus de migration vers une destination internationale.
