### ISSUE TITLE
New data source for 16.1.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#17]
The current source in the GIF links to a table with no gender breakdown. [Suggested new source ](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3510015601) has gender and Indigenous identity breakdown.

Looking for confirmation that I can use new source instead of the current one

**Comment by catherinemichaud** [comment]
Same survey, different way to display the data. You can use either/both. Please document any change.

**Comment by MaiaPelletier** [comment]
done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/f917742078d8b98b1024aa6abfbca1e7333f57d1
