### ISSUE TITLE
8.4.1 / 12.2.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#176]
12.2.1 Material footprint, material footprint per capita, and material footprint per GDP

**Methodology from official UN SDG metadata:**

> 𝑀𝐹 = 𝐷𝐸 + 𝑅𝑀𝐸𝐼𝑀 − 𝑅𝑀𝐸𝐸X
> 
> Where:
> 𝑀𝐹 – material footprint;
> 𝐷𝐸 – domestic extraction of materials (biomass, fossil fuels, metal ores and non-metallic minerals);
> 𝑅𝑀𝐸𝐼𝑀 – raw material equivalent of imports;
> 𝑅𝑀𝐸𝐸𝑋 – raw material equivalents of exports.

I think between the [Annual Mineral Production Survey](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1610002201), the [Annual Oil and Gas Extraction Survey](http://www23.statcan.gc.ca/imdb/p2SV.pl?Function=getSurvey&amp;SDDS=2178), and [Table 12-10-0121-01  International merchandise trade by commodity, monthly (x 1,000,000)](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210012101), we have all the information needed to calculate this indicator, as well as 12.2.2 (#27 ). It will highly likely require a custom tabulation from subject matter, as the data doesn't seem to be available and they can better define the difference between "_direct imports_" and "_raw material equivalent of imports_".

**Comment by catherinemichaud** [comment]
- [ ] FR définition: L'empreinte matérielle (EM) est l'attribution de l'extraction globale de matériaux à la demande finale intérieure d'un pays. L'empreinte matérielle totale est la somme des empreintes matérielles de la biomasse, des combustibles fossiles, des minerais métalliques et des minerais non métalliques.
- [ ] méthode calcul: Les données ont été tabulées pour rendre compte de cet indicateur comme spécifié par les métadonnées. Veuillez vous référer aux sources pour obtenir des informations supplémentaires sur les métadonnées ou la source.

Empreinte matérielle (EM) = Extraction nationale de matériaux + équivalent en matières premières des importations - équivalent en matières premières des exportations

Empreinte matérielle par habitant = DMC/population totale

DMC par PIB = DMC/PIB en dollars chaînés de 2017
