### ISSUE TITLE
Data gap 8.4.1 / 12.2.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#194]
- [x] Use Table_E from custom tabulation excel (RMC line)
- [x] Use [Population Estimates](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710000501) for per capita series (in tonnes)
- [x] Use [GDP ](https://doi.org/10.25318/3610036901-eng) for per GDP series (kilograms)

**Comment by camereb** [comment]
8.4.1 done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/9d78c582bf9a0980d8c7a2ec8e9e4a8b388626db

**Comment by camereb** [comment]
12.2.1 done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/2709b8dd18e25595979a8a60b8a47f47062e23d5
