### ISSUE TITLE
Update hub to version 2.2.0

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#197]
We received errors when we tried to update to 2.2.0 this week ([see log here](https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/actions/runs/5191701372/jobs/9359867358)). Need to investigate and/or try update again.

**Comment by JulienSTC** [comment]
Updated successfully.
