### ISSUE TITLE
GRIP 2.1.2

### ISSUE THREAD

**Issue by sdg-data-canada-odd-donnees** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#226]
Add the following CODR to the data source for this indicator as it provides additional disaggregation.
https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1310083501

**Comment by catherinemichaud** [comment]
- Also add the territories: 
- [ ] [Canadian Income Survey: Territorial estimates, 2020](https://www150.statcan.gc.ca/n1/en/daily-quotidien/221103/dq221103d-eng.pdf?st=-1WriuZ8), 
- [ ] [Canadian Income Survey: Territorial estimates, 2021](https://www150.statcan.gc.ca/n1/daily-quotidien/230621/dq230621c-eng.htm)

And

- [ ] Proxy name to change to Proportion of persons
- [ ] Chart title name to change from family to persons

**Comment by catherinemichaud** [comment]
- [ ] FR: Drop down menu on the left, Demographic characteristics still in English and some sub-categories also in English
- [ ] Is there a way to present the information in a more user friendly way? the economic family type and demographic characteristics options are overwhelming
- [ ] Both languages:  I tried to select sub-series under Demographic characteristics, and nothing appears on the graph. The columns aren't appearing in the table either
- [ ] FR: Under National metadata, the indicator category should display the name of the proxy

**Comment by catherinemichaud** [comment]
Remove category and data "Population aged 15 years and over"
