### ISSUE TITLE
Old data source for 7.1.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#25]
GIF links to 2015 data (7 years old) for household use of electricity. This table reports the same number as the GIF currently reports and also all iterations of data released since: [Table 25-10-0060-01  Household energy consumption, Canada and provinces](https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=2510006001)

Recommendation: Change source for 7.1.1 to this CODR table from the same STC statistical program

**Comment by catherinemichaud** [comment]
Agreed. There are some interesting disaggregation too.

**Comment by catherinemichaud** [comment]
request sent - pending

**Comment by JulienSTC** [comment]
Statistics Canada. Table 25-10-0060-01  Household energy consumption, Canada and provinces
DOI: https://doi.org/10.25318/2510006001-eng

Also per type of dwelling:
Statistics Canada. Table 25-10-0061-01  Household energy consumption, by type of dwelling, Canada and provinces
DOI: https://doi.org/10.25318/2510006101-eng

**Comment by MaiaPelletier** [comment]
done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/96f41e00684a56eb44d0094f251f8e3f1042afbc
