### ISSUE TITLE
Methodology for 8.4.2 / 12.2.2

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#27]
This one has 8 sub-indicators. I need clarification which variables to use for this data. I can't seem to locate numbers that match the data currently reported in the GIF.

**Comment by MaiaPelletier** [comment]
From CM:

> i'm not sure how i feel about that proxy - there is room for improvement and with the new SEEA (System of Environmental-Economic Accounting) i think we can have a closer proxy if not the actual indicator

**Comment by catherinemichaud** [comment]
As per my comment from Feb 10, let's meet with SME to see if there are new data available and propose a change in the proxy

**Comment by JulienSTC** [comment]
Data sheet from a request in the data gap folder. SMEs identified in SDG box. Needs verification.

**Comment by MaiaPelletier** [comment]
Was the data ever verified?

**Comment by MaiaPelletier** [comment]
From JL on #159 (duplicate issue) 

Potential:
Statistics Canada. Table 38-10-0096-01 Physical flow account for energy use
DOI: https://doi.org/10.25318/3810009601-eng

Statistics Canada. Table 38-10-0250-01 Physical flow account for water use (x 1,000)
DOI: https://doi.org/10.25318/3810025001-eng

Statistics Canada. Table 38-10-0150-02 Pilot physical flow account for plastic material, by province and territory
DOI: https://doi.org/10.25318/3810015001-eng

**Comment by MaiaPelletier** [comment]
Use custom tabulation in data gap folder to report these indicators

**Comment by camereb** [comment]
Done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/f8f82aad024b07ca8e584e3d9f03a13e6e80958a
