### ISSUE TITLE
New source for 7.2.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#28]
The source for 7.2.1 is a long PDF file and the data reported in the GIF is not directly from the report (potentially the data in the GIF is wrong). 

We report this data in the CIF and seeking approval to use the source from the CIF: 

- [CIF Indicator](https://sdgcif-data-canada-oddcic-donnee.github.io/7-3-1/)
- [Source](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2510002001)

**Comment by catherinemichaud** [comment]
duplicate issue
