### ISSUE TITLE
1.5.3 / 11.b.1 / 13.1.2

### ISSUE THREAD

**Issue by catherinemichaud** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#287]
Add Proxy

- [ ] EN: National disaster risk reduction strategies in line with the Sendai Framework for Disaster Risk Reduction 2015–2030 adopted and implemented
- [ ] FR: Stratégies nationales de réduction des risques de catastrophe conforment au Cadre d'action de Sendai pour la réduction des risques de catastrophe (2015-2030) qui ont été adoptées et implémentées

- [ ] FR Source is in EN, please change to FR

**Comment by Zelheim** [comment]
For the French proxy title, I have changed it from "Stratégies nationales de réduction des risques de catastrophe **conforment** au Cadre d'action de Sendai pour la réduction des risques de catastrophe (2015-2030) qui ont été adoptées et implémentées" to "Stratégies nationales de réduction des risques de catastrophe **conformes** au Cadre d'action de Sendai pour la réduction des risques de catastrophe (2015-2030) qui ont été adoptées et implémentées"!

**Comment by catherinemichaud** [comment]
Need the proxy blurb under the comments and limitation (in national metadata) in both languages
