### ISSUE TITLE
ALL OECD data sources

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#34]
OECD data is hard to navigate and we are often unable to find where the numbers in the current GIF come from. Here is a list of all the indicators that use OECD data:

- [x] 2.a.2 (#10 )
- [x] 4.b.1 (#143 )
- [x] 6.a.1 (#149 )
- [x] 7.a.1 (#158 )
- [x] 8.a.1.a (#152 )
- [x] 8.a.1.b (#152 )
- [x] 10.b.1 (#174 )
- [ ] 15.a.1.a (#180 )
- [x] 15.b.1 (#166 )
- [x] 17.19.1 (#50 )
- [x] 17.2.1.a (#122 )
- [x] 17.2.1.b (#122 )
- [ ] 17.3.1.a
- [ ] 17.3.1.b
- [ ] 17.9.1

**Comment by catherinemichaud** [comment]
Step 1 - Assess if data exists within STC. (see below)
Step 2 - Find a contact in OECD 

Step #1

- 2.a.2 - Has its own issue logged
- 4.b.1 - See issue for 2.a.2
- 6.a.1 - See issue for 2.a.2
- 7.a.1 - See issue for 2.a.2
- 8.a.1.a - GAC?
- 8.a.1.b - GAC?
- 15.a.1.a - See issue for 2.a.2
- 15.b.1 - See issue for 2.a.2
- 17.19.1 - We might have that data in the Bilat section - Created an issue
- 17.2.1.a - See issue for 2.a.2
- 17.2.1.b - See issue for 2.a.2
- 17.3.1.a - GAC?
- 17.3.1.b - See issue for 2.a.2
- 17.9.1- GAC?

**Comment by JulienSTC** [comment]
For 17.9.1: https://www.oecd-ilibrary.org/sites/2dcf1367-en/1/3/2/5/index.html?itemId=/content/publication/2dcf1367-en&_csp_=177392f5df53d89c9678d0628e39a2c2&itemIGO=oecd&itemContentType=book

**Comment by MaiaPelletier** [comment]
All indicators have their own assigned issue
