### ISSUE TITLE
Source for 1.5.1 / 11.5.1 / 13.1.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#35]
Olaide and I had difficulties locating where the numbers for this indicator come from in this source

**Comment by catherinemichaud** [comment]
contact [The Canadian Disaster Database](https://www.publicsafety.gc.ca/cnt/rsrcs/cndn-dsstr-dtbs/index-en.aspx)

**Comment by JulienSTC** [comment]
Potential source for natural disaster death (which aligns with the UN's definition of natural disaster source: https://www.who.int/docs/default-source/gho-documents/global-health-estimates/ghe2019_cod_methods.pdf)

Statistics Canada. Table 13-10-0156-01  Deaths, by cause, Chapter XX: External causes of morbidity and mortality (V01 to Y89)
DOI: https://doi.org/10.25318/1310015601-eng
ICD-10 Codes X33 to X39

**Comment by JulienSTC** [comment]
CDD team has been contacted.

**Comment by MaiaPelletier** [comment]
data added for 1.5.1 in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/59482109aca148337294464f3a2ba46ca208027c

data manipulation needs to be double-checked. the indicator shows the number of people directly affected by floods to be higher than the number of people directly affected by all disasters total, which is impossible.

**Comment by camereb** [comment]
Numbers updated and done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/06bec124080d16b6b12b148bbada9686362ad7f3
