### ISSUE TITLE
Methodology for 9.b.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#38]
The data linked in the current GIF hub is reported in yearly periods but the data source linked reports data monthly. How are the monthly numbers summarized to yearly values?

**Comment by catherinemichaud** [comment]
Check official metadata to confirm reference period. We publish annual table - check CIF (goal 8 and/or 9) for table number.

**Comment by catherinemichaud** [comment]
I think the current data source is wrong completely.

**Comment by catherinemichaud** [comment]
Request sent - pending

**Comment by JulienSTC** [comment]
Principal statistics for manufacturing industries, by North American Industry Classification System (NAICS) (x 1,000)
Table: 16-10-0117-01
Statistics = Manufacturing Value Added
NAICS sum(325, 333, 334, 335, 336, 3391)/Manufacturing 31-33 (total MFA)

**Comment by JulienSTC** [comment]
SME contacted for confirmation.

**Comment by JulienSTC** [comment]
SME confirmed the source and NAICS selection

**Comment by MaiaPelletier** [comment]
done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/341c4493037119fdd292228e579c29e0e761628c
