### ISSUE TITLE
New source for 2.1.2

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#47]
GIF 2.1.2 is proxy indicator that matches 2.1.1 in CIF. Recommend switching source to match CIF source ([Table: 13-10-0834-01](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1310083401)).

- [x] update data in GIF data hub
- [x] write note documenting change

**Comment by catherinemichaud** [comment]
Agreed. Please include a note explaining the change in the data source.

**Comment by MaiaPelletier** [comment]
Done in merge https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/pull/62
