### ISSUE TITLE
new source for 7.2.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#49]
proposal: use CIF source for 7.3.1 because the indicators are the same

**Comment by catherinemichaud** [comment]
request sent - pending

**Comment by catherinemichaud** [comment]
Confirmed with SME. Please use table 25-10-0015 and annualize the data before calculating the proportion. Example for RY2020 provided in email "RE: Energy data for reporting on the Sustainable Development Goals" send to the SDG mailbox on 2023.02.28 at 9:22am.

**Comment by MaiaPelletier** [comment]
done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/bfee3fca1d97fe65157c9dd98a472c5bc0b3dfcb
