### ISSUE TITLE
GRIP 1.3.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#5]
See last comment below.

**Comment by catherinemichaud** [comment]
Same for me. Ask Duane for his SME contact please.

**Comment by catherinemichaud** [comment]
I think a lot of them are custom tabs. We will need to contact SMEs

**Comment by JulienSTC** [comment]
Unsure if this would answer any specifically but CPOP has a lot: Statistics Canada. Table 98-10-0068-01  Income statistics for detailed income sources and taxes by age and gender: Canada, provinces and territories, census metropolitan areas and census agglomerations with parts - DOI: https://doi.org/10.25318/9810006801-eng

**Comment by JulienSTC** [comment]
1.3.1.c  Proportion of older persons receiving a pension
Statistics Canada. Table 11-10-0053-01  Sources of income of senior census families by family type and age of older partner, parent or individual
DOI: https://doi.org/10.25318/1110005301-eng
Source: [Annual Income Estimates for Census Families and Individuals (T1 Family File) (statcan.gc.ca)](https://www150.statcan.gc.ca/n1/en/surveys/4105?sourcecode=4105&p=0-Data#data)

**Comment by JulienSTC** [comment]
1.3.1.f Proportion of employed labour force eligible for workers' compensation benefits
	[Canadian Workers’ Compensation System – Year at a Glance | AWCBC / ACATC](https://awcbc.org/en/statistics/canadian-workers-compensation-system-year-at-a-glance/)
Data up to 2021 available

**Comment by JulienSTC** [comment]
SME Contacted for updated data, fill data gaps.

**Comment by JulienSTC** [comment]
SME has been contacted, updated data for the ones from the EI survey and CIS will be provided around May 5th. Can proceed with copying over the older data points for now.

**Comment by MaiaPelletier** [comment]
old data points added in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/fabaf4ec2fed00c05cfdacdddeac21d560e752cd, waiting for SME for data update 🙂

**Comment by JulienSTC** [comment]
Custom tabulation 2021 data received from SMEs based on the last CIS, file (name = SDGs_Final) in data gap folder. Please review what was provided and align with the proper sub-indicator. Let me know if we need to seek clarifications from SMEs.

**Comment by catherinemichaud** [comment]
Please update series' name to align with UN metadata.
data is here: https://gcdocs.gc.ca/statcan/llisapi.dll?func=ll&objaction=overview&objid=31961912

**Comment by JulienSTC** [comment]
Update indicator:

Data are here: https://gcdocs.gc.ca/statcan/llisapi.dll?func=ll&objaction=overview&objid=31961912

Only include series F and those in sheet 1 of the Excel aligned to the the series. 

- [ ] **Series a:**
- Update title to: Proportion of population covered by at least one social protection cash benefit
- 2021 data in sheet

- [ ] **Series b**
- Update title to: Proportion of children covered by social protection benefits
- data in hub ok for 2015 and 2018, 2021 in Excel

- [ ] **Series d - Proxy**
- Update title to: Proportion of persons with disabilities receiving benefits
- Add proxy banner - update text to reflect that only 1 indicator is a proxy
- Add in comment and limitations the detail - Look at the excel and metadata for the wording
- 2021 Data in Excel
- 
- [ ] **Series f**
- update title to: Proportion of workers covered in case of employment injury
- data are ok - look for updated ones on the website

- [ ] **Series g**
- Update title to: Proportion of older persons receiving a pension
- Update data to the ones in the Excel (2021 + 2018)

- [ ] **Series h**
- Update title to: Proportion of vulnerable persons receiving benefits
- 2021 data in Excel

- [ ] **Series i**
- Update title to: Proportion of poor population receiving social assistance cash benefit
- Data in Excel

- [ ] Remove other series not featured above. Update information and the FR pages accordingly.

**Comment by Zelheim** [comment]
Only the series "Proportion of workers covered in case of employment injury" has geographical disaggregation and geocodes. All the other series only has national level data (no geocodes when it's Canada), so they will not be displayed on the map.

**Comment by Zelheim** [comment]
I looked into the documentation and I don't believe that's an option unfortunately. We could either keep the map or turn it off entirely.

**Comment by JulienSTC** [comment]
Update:
- EN page remove from def and concept: An economic family refers to a group of two or more persons who live in the same dwelling and are related to each other by blood, marriage, common-law, adoption or a foster relationship.
- FR page remove from def and concept: Une famille économique est constituée d’un groupe de deux personnes ou plus qui vivent dans le même logement et qui sont apparentées par le sang, par alliance, par union libre, par adoption ou par une relation de famille d’accueil.
- EN page add to def and concept at the begining: The indicator reflects the proportion of persons effectively covered by a social protection system, including social protection floors. It also reflects the main components of social protection: child and maternity benefits, support for persons without a job, persons with disabilities, victims of work injuries and older persons.
- FR Page add to def and concept at the beginning: L'indicateur reflète la proportion de personnes effectivement couvertes par un système de protection sociale, y compris les seuils de protection sociale. Il reflète également les principales composantes de la protection sociale : allocations familiales et de maternité, soutien aux personnes sans emploi, aux personnes handicapées, aux victimes d'accidents du travail et aux personnes âgées.
