### ISSUE TITLE
GRIP 1.a.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#58]
**1.a.1 Total official development assistance grants from all donors that focus on poverty reduction as a share of the recipient country's gross national income**

**Comment by catherinemichaud** [comment]
Lots of information in the last 2 reports here https://www.international.gc.ca/transparency-transparence/international-assistance-report-stat-rapport-aide-internationale/index.aspx?lang=eng&_ga=2.213975829.340912999.1620834816-2016260363.1604978633
I'll try to get us a contact at GAC, but we could also consider a proxy and use $$ related to Goal 1

**Comment by catherinemichaud** [comment]
- Remove Source 2
- Update Source 1 to OECD Data Explorer, https://data-explorer.oecd.org/
- Update Definition and Concept to add:
 Basic social services and development food aid, which focus on poverty reduction, are defined using the
following OECD Creditor Reporting System purpose codes, which identify the sector the activity is
intended to target:
• Basic Education (CRS codes 112xx)
• Basic Health (CRS codes (122xx)
• Water Supply and Sanitation (CRS codes 140xx)
• Multisector aid for basic social services (CRS code 16050)
• Development Food Aid (CRS code 52010)

- Update Method of computation with 
100* (Basic Education + Basic Health + Water Supply and Sanitation + Development Food Aid) / GNI

Step to get data: From OECD Data Explorer, click on ODA. In the filters, select:
Donor=Canada
Sector = what is above (I couldn't find 16050)

**Comment by tristanmenard** [comment]
@catherinemichaud the new link provided for source 1 points to the OECD's Aid (ODA) by sector and donor table, and not the Creditor Reporting System table. These seem to be related but there are a few key differences. For example, the Aid (ODA) by sector and donor table does not a "Multisector aid for basic social services" sector option. Also, the Aid (ODA) by sector and donor table provides only values for ODA commitments, while the Creditor Reporting System provides values for both commitments and disbursements. Do we want to track ODA commitments or disbursements?

**Comment by tristanmenard** [comment]
What is the source for the GNI?

**Comment by tristanmenard** [comment]
@catherinemichaud @JulienSTC 
Confirm whether ODA grant values should be taken from 
* [CRS: Creditor Reporting System (flows)](https://data-explorer.oecd.org/vis?pg=0&bp=true&snb=19&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_CRS%40DF_CRS&df[ag]=OECD.DCD.FSD&df[vs]=1.1&dq=CAN.DPGC.52010%2B16050%2B140%2B122%2B112.11._T._T.D.Q._T..&pd=2015%2C&to[TIME_PERIOD]=false&vw=tb&lc=en)
  * Donor = Canada
  * Recipient = Developing countries
  * Sector = Basic education/Basic health/Water supply & sanitation/Multisector aid for basic social services/Food assistance
  * Measure = ODA Grants
  * Flow type = Disbursements
  * Price base = Constant prices

OR

* [CRS: Creditor Reporting System (grant equivalent)](https://data-explorer.oecd.org/vis?lc=en&fs[0]=Topic%2C1%7CDevelopment%23DEV%23%7COfficial%20Development%20Assistance%20%28ODA%29%23DEV_ODA%23&fs[1]=Donor%2C0%7CCanada%23CAN%23&fs[2]=Sector%2C4%7CAll%20sectors%231000%23%7CSector%20allocable%23450%23%7CSocial%20infrastructure%20and%20services%23100%23%7CEducation%23110%23%7CBasic%20education%23112%23&fs[3]=Sector%2C4%7CAll%20sectors%231000%23%7CSector%20allocable%23450%23%7CSocial%20infrastructure%20and%20services%23100%23%7CHealth%23120%23%7CBasic%20health%23122%23&fs[4]=Sector%2C3%7CAll%20sectors%231000%23%7CSector%20allocable%23450%23%7CSocial%20infrastructure%20and%20services%23100%23%7CWater%20supply%20%26%20sanitation%23140%23&fs[5]=Sector%2C4%7CAll%20sectors%231000%23%7CSector%20allocable%23450%23%7CSocial%20infrastructure%20and%20services%23100%23%7COther%20social%20infrastructure%20and%20services%23160%23%7CMultisector%20aid%20for%20basic%20social%20services%2316050%23&pg=0&fc=Flow%20type&snb=8&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_GREQ%40DF_CRS_GREQ&df[ag]=OECD.DCD.FSD&df[vs]=1.1&dq=CAN.DPGC.52010%2B112%2B122%2B140%2B16050.91._T._T..Q._T..&pd=%2C&to[TIME_PERIOD]=false&ly[cl]=TIME_PERIOD&ly[rw]=SECTOR&vw=tb)
  * Donor = Canada
  * Recipient = Developing countries
  * Sector = Basic education/Basic health/Water supply & sanitation/Multisector aid for basic social services/Food assistance
  * Measure = ODA Grants
  * Price base = Constant prices

Confirm that method of computation should be
100 * (Basic Education + Basic Health + Water Supply and Sanitation + Development Food Aid **+ Multisector aid for basic social services**) / GNI

Confirm which of `Food assistance (CRS code 52010)` or `Development Food Aid (CRS code 520xx)` should be used? UN metadata calls for `Development Food Aid (CRS code 52010)` but it does not exist.

Confirm GNI source: [DAC1: Flows by donor (ODA+OOF+Private)](https://data-explorer.oecd.org/vis?lc=en&fs[0]=Topic%2C1%7CDevelopment%23DEV%23%7COfficial%20Development%20Assistance%20%28ODA%29%23DEV_ODA%23&fs[1]=Donor%2C0%7CCanada%23CAN%23&fs[2]=Measure%2C0%7CGross%20National%20Income%20%28GNI%29%231%23&pg=0&fc=Measure&snb=1&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_DAC1%40DF_DAC1&df[ag]=OECD.DCD.FSD&df[vs]=1.2&dq=CAN.1....Q.&pd=2015%2C&to[TIME_PERIOD]=false&vw=tb)

**Comment by JulienSTC** [comment]
Can't open either links. DId my own exploring and I think it should be close to the second option above (should only include grants).
1. 
Donor = Canada
Recipient = Developing countries
Sector = Basic education/Basic health/Water supply & sanitation/Multisector aid for basic social services/**Development** Food assistance
Measure = ODA Grants
Price base = Constant prices
2. Yes but update Food assistance to use "Development food assistance"
3. Yes for GNI
4. I obtain 0.0521% for 2022 - does that line up with your result?

**Comment by tristanmenard** [comment]
- removed broken/redirected link to http://www.oecd.org/dac/stats/purposecodessectorclassification.htm in definition
- replaced broken/redirected link to http://www.oecd.org/dac/stats/officialdevelopmentassistancedefinitionandcoverage.htm in definition EN/FR with https://www.oecd.org/en/topics/sub-issues/oda-eligibility-and-conditions/official-development-assistance--definition-and-coverage.html EN and https://www.oecd.org/fr/topics/sub-issues/oda-eligibility-and-conditions/official-development-assistance--definition-and-coverage.html FR
