### ISSUE TITLE
New data source 6.3.1

### ISSUE THREAD

**Issue by catherinemichaud** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#67]
Investigate https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3810006001

**Comment by JulienSTC** [comment]
6.3.1: Table: 38-10-0060-01

**Comment by JulienSTC** [comment]
This seems to have a lot of data for Canada.

**Comment by MaiaPelletier** [comment]
- [ ] Populate indicator with data from CODR for industrial portion of the indicator
- [ ] Research more on UN water data for domestic portion of the indicator

**Comment by JulienSTC** [comment]
Municipal: 
Statistics Canada. Table 38-10-0124-01  Wastewater volumes discharged from municipal sewage systems by treatment category (x 1,000,000)

**Comment by MaiaPelletier** [comment]
done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/96dd595b24afed69d64e3885e7e8b7140869633a
