### ISSUE TITLE
Data gap 11.7.2

### ISSUE THREAD

**Issue by catherinemichaud** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#81]
I am pretty sure i saw some data or article from SPPSS that could be used to populate this indicator. Please investigate.

**Comment by MaiaPelletier** [comment]
Chart 1 from SSPPS approved for source 🙂

**Comment by camereb** [comment]
Done in https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/commit/a91d00b5c8c3422e93d92c4e36930366a2579008
